services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules        # pour ne pas écraser node_modules dans le conteneur
    command: ng serve --host 0.0.0.0 --poll=2000 --proxy-config proxy.conf.json
    environment:
      - CHOKIDAR_USEPOLLING=true


  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/spellwiki
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=spellwiki

  
  db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spellwiki
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data: